# name: Report

# on:
#   schedule:
#     - cron: '0 12 * * *'

# jobs:

#   nightly-report:
#     name: Update Github page
#     runs-on: ubuntu-latest
#     if: false
#     steps:
#       - name: Checkout Arrow
#         shell: bash
#         run: git clone https://github.com/apache/arrow
#       - name: Checkout Crossbow
#         shell: bash
#         run: git clone https://github.com/ursa-labs/crossbow
#       - name: Setup Conda
#         uses: s-weigand/setup-conda@v1
#         with:
#           conda-channels: "conda-forge"
#       - name: Install Dependencies
#         shell: bash
#         run: conda install -y --file arrow/ci/conda_env_crossbow.txt
#       - name: Send Report
#         shell: bash
#         env:
#           CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
#         run: arrow/dev/tasks/crossbow.py github-page generate -n 20
